# Generated by Django 3.0.7 on 2020-09-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlist',
            name='facility',
            field=models.CharField(choices=[('Assisted', 'ALF'), ('Independent', 'IND'), ('AdultDay', 'ADC'), ('Home', 'HOME')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientlist',
            name='order',
            field=models.CharField(choices=[('PT', 'PT Eval'), ('OT', 'OT Eval'), ('SLP', 'SLP Eval')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientlist',
            name='setting',
            field=models.CharField(choices=[('workers_Comp', 'WC'), ('homeHealth', 'HH'), ('medicareB', 'MB')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='discpline',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
