# Generated by Django 3.0.7 on 2020-10-02 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0002_auto_20200929_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlist',
            old_name='zip',
            new_name='zipCode',
        ),
        migrations.AlterField(
            model_name='staff',
            name='discpline',
            field=models.CharField(choices=[('PT', 'PT'), ('OT', 'OT'), ('SLP', 'SLP'), ('PTA', 'PTA'), ('COTA', 'COTA')], max_length=20, null=True),
        ),
    ]
