# Generated by Django 3.0.7 on 2020-10-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0003_auto_20201001_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(choices=[('Schedule', 'Schedule'), ('Eval', 'Eval'), ('Follow up', 'Follow up'), ('Discharge', 'Discharge')], max_length=20, null=True)),
            ],
        ),
    ]
