# Generated by Django 3.0.7 on 2020-10-06 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('total', '0009_auto_20201005_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='usericon.png', null=True, upload_to='')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('userLicense', models.CharField(max_length=11, null=True)),
                ('discpline', models.CharField(choices=[('PT', 'PT'), ('OT', 'OT'), ('SLP', 'SLP'), ('PTA', 'PTA'), ('COTA', 'COTA')], max_length=20, null=True)),
                ('npi', models.CharField(max_length=11, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='staff',
        ),
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='total.PatientList'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='order',
            name='emp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='total.Emp'),
        ),
    ]
